name: "Tests"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Set up Python"
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.10"
          cache: "pip"

      - name: "Install requirements"
        run: python3 -m pip install -r requirements_test.txt

      - name: "Run"
        run: python3 -m pytest